{% set name = "xeus-python" %}
{% set version = "0.17.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xeus-python/archive/{{ version }}.tar.gz
  sha256: 5b465638561019469c32974998b6f4bcde0b38c243c0b6f50bc5b001a4d78b4f

build:
  number: 0
  skip: true  # [(win and vc<14) or py==36]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:
    - python
    - xeus-zmq >=3.1.0,<4.0
    - pybind11 >=2.6.1,<3.0
    - nlohmann_json >=3.11.3,<4
    - pybind11_json >=0.2.6,<0.3
  run:
    - python
    - xeus-python-shell >=0.6.3,<0.7
    - debugpy >=1.1.0,<2.0  # [py>=37]
    - pygments >=2.3.1,<3

test:
  commands:
    - test -f ${PREFIX}/bin/xpython                                                              # [unix]
    - test -f ${PREFIX}/share/jupyter/kernels/xpython/kernel.json                                # [unix]
    - test -f ${PREFIX}/share/jupyter/kernels/xpython-raw/kernel.json                            # [unix]
    - if not exist %LIBRARY_BIN%\\xpython.exe (exit 1)                                           # [win]
    - if not exist %LIBRARY_PREFIX%\\share\\jupyter\\kernels\\xpython\\kernel.json (exit 1)      # [win]
    - if not exist %LIBRARY_PREFIX%\\share\\jupyter\\kernels\\xpython-raw\\kernel.json (exit 1)  # [win]
    - test -d ${PREFIX}/include/xeus-python                                                      # [unix]
    - test -f ${PREFIX}/include/xeus-python/xinterpreter.hpp                                     # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-python/xeus-pythonConfig.cmake                            # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-python/xeus-pythonConfigVersion.cmake                     # [unix]
    - if not exist %LIBRARY_INC%\\xeus-python\\xinterpreter.hpp (exit 1)                         # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\xeus-python\\xeus-pythonConfig.cmake (exit 1)           # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\xeus-python\\xeus-pythonConfigVersion.cmake (exit 1)    # [win]
    # The kernel spec in installed in the general PREFIX
    - if not exist %PREFIX%\\share\\jupyter\\kernels\\xpython\\kernel.json (exit 1)              # [win]
    - if not exist %PREFIX%\\share\\jupyter\\kernels\\xpython-raw\\kernel.json (exit 1)          # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter kernel for the Python programming language based on Xeus
  description: xeus-python is a Jupyter kernel for the Python programming language based on the Xeus library, a native implementation of the Jupyter protocol.
  doc_url: http://xeus-python.readthedocs.io
  dev_url: https://github.com/jupyter-xeus/xeus-python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
    - trungleduc
