{% set name = "xeus-python" %}
{% set version = "0.5.1" %}
{% set sha256 = "84240569e4e9f996766338df4260ac95352bedada07f60c1e9093e79c0f75104" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xeus-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - cppzmq >=4.3.0,<4.4.0
    - zeromq >=4.2.5,<4.4.0
    - xtl >=0.6.0,<0.7
    - xeus >=0.23.2,<0.24.0
    - pybind11 >=2.2.4,<3.0
    - nlohmann_json >=3.3.0,<4.0
  run:
    - python
    - jedi >=0.13.1,<0.14
    - pygments >=2.3.1,<3.0.0

test:
  commands:
    - test -f ${PREFIX}/bin/xpython                                                                      # [unix]
    - test -f ${PREFIX}/share/jupyter/kernels/xpython/kernel.json                                        # [unix]
    - if exist %LIBRARY_BIN%\\xpython.exe (exit 0) else (exit 1)                                         # [win]
    - if exist %LIBRARY_PREFIX%\\share\\jupyter\\kernels\\xpython\\kernel.json (exit 0) else (exit 1)    # [win]
    - test -d ${PREFIX}/include/xeus-python                                                              # [unix]
    - test -f ${PREFIX}/include/xeus-python/xinterpreter.hpp                                             # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-python/xeus-pythonConfig.cmake                                    # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-python/xeus-pythonConfigVersion.cmake                             # [unix]
    - if exist %LIBRARY_INC%\\xeus-python\\xinterpreter.hpp (exit 0) else (exit 1)                       # [win]
    - if exist %LIBRARY_LIB%\\cmake\\xeus-python\\xeus-pythonConfig.cmake (exit 0) else (exit 1)         # [win]
    - if exist %LIBRARY_LIB%\\cmake\\xeus-python\\xeus-pythonConfigVersion.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\\..\\share\\jupyter\\kernels\\xpython\\kernel.json (exit 0) else (exit 1)            # [win]

about:
  home: http://quantstack.net/xeus-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Jupyter kernel for the Python programming language based on xeus'
  description: 'xeus-python is a Jupyter kernel for Python based on the native implementation of the Jupyter protocol xeus.'
  doc_url: http://xeus-python.readthedocs.io
  dev_url: https://github.com/QuantStack/xeus-python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
