{% set name = "xeus-python" %}
{% set version = "0.8.0" %}
{% set sha256 = "816d9d6cb6897495b1bd36c69bb6d6d4c15295bf3c260c9c213c2ec963bbb426" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xeus-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - python
    - cppzmq >=4.4.1,<5
    - zeromq >=4.2.5,<4.4.0
    - xtl >=0.6.8,<0.7
    - xeus >=0.24.0,<0.25.0
    - pybind11 >=2.2.4,<3.0
    - nlohmann_json >=3.3.0,<4.0
    - pybind11_json >=0.2.2,<0.3
  run:
    - python
    - jedi >=0.15.1,<0.16
    - pygments >=2.3.1,<3.0.0
    - ptvsd                        # [win and py<38]
    - ptvsd                        # [unix]

test:
  commands:
    - test -f ${PREFIX}/bin/xpython                                                                      # [unix]
    - test -f ${PREFIX}/share/jupyter/kernels/xpython/kernel.json                                        # [unix]
    - if exist %LIBRARY_BIN%\\xpython.exe (exit 0) else (exit 1)                                         # [win]
    - if exist %LIBRARY_PREFIX%\\share\\jupyter\\kernels\\xpython\\kernel.json (exit 0) else (exit 1)    # [win]
    - test -d ${PREFIX}/include/xeus-python                                                              # [unix]
    - test -f ${PREFIX}/include/xeus-python/xinterpreter.hpp                                             # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-python/xeus-pythonConfig.cmake                                    # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-python/xeus-pythonConfigVersion.cmake                             # [unix]
    - if exist %LIBRARY_INC%\\xeus-python\\xinterpreter.hpp (exit 0) else (exit 1)                       # [win]
    - if exist %LIBRARY_LIB%\\cmake\\xeus-python\\xeus-pythonConfig.cmake (exit 0) else (exit 1)         # [win]
    - if exist %LIBRARY_LIB%\\cmake\\xeus-python\\xeus-pythonConfigVersion.cmake (exit 0) else (exit 1)  # [win]
    # The kernel spec in installed in the general PREFIX
    - if exist %PREFIX%\\share\\jupyter\\kernels\\xpython\\kernel.json (exit 0) else (exit 1)            # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter kernel for the Python programming language based on xeus
  description: xeus-python is a Jupyter kernel for Python based on the native implementation of the Jupyter protocol xeus.
  doc_url: http://xeus-python.readthedocs.io
  dev_url: https://github.com/jupyter-xeus/xeus-python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
