context:
  version: "0.17.5"
  build_number: 0

package:
  name: xeus-python
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-python/archive/${{ version }}.tar.gz
  sha256: 5efd62af29cac84484ea3116c7c7fd1ae7630e4ad085057934f9e61d454ed673

build:
  number: ${{ build_number }}

requirements:
  run_exports:
    - ${{ pin_subpackage('xeus-python', upper_bound='x.x') }}
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11
    - if: unix
      then:
        - make
  host:
    - python
    - xeus-zmq >=3.1.1,<4.0
    - pybind11 >=2.6.1,<3.0
    - pybind11_json >=0.2.6,<0.3
    - nlohmann_json
    - nlohmann_json-abi
  run:
    - python
    - xeus-python-shell >=0.6.3,<0.7
    - debugpy >=1.1.0,<2.0
    - pygments >=2.3.1,<3

tests:
  - package_contents:
      files:
        exists:
          - ${{ "Library/" if win }}bin/xpython${{ ".exe" if win }}
          - ${{ "Library/" if win }}share/jupyter/kernels/xpython/kernel.json
          - ${{ "library/" if win }}share/jupyter/kernels/xpython-raw/kernel.json
          - ${{ "library/" if win }}include/xeus-python/xinterpreter.hpp
          - ${{ "library/" if win }}lib/cmake/xeus-python/xeus-pythonConfig.cmake
          - ${{ "library/" if win }}lib/cmake/xeus-python/xeus-pythonConfigVersion.cmake

about:
  homepage: https://github.com/jupyter-xeus/xeus-python
  repository: https://github.com/jupyter-xeus/xeus-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter kernel for the Python programming language based on Xeus
  description: xeus-python is a Jupyter kernel for the Python programming language based on the Xeus library, a native implementation of the Jupyter protocol.
  documentation: http://xeus-python.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
    - trungleduc
