travis:
  secure:
    BINSTAR_TOKEN: QGjrs+deswRtzWXQ2qHzJN7R7iJvgyU1BbKYTnzbwk+fZp8MnknV2fyB1XxJCWeiC17y9WhaddyXEQ5kpYGoAVEfkjAvQggIf6xawgR2H76zJmC6UGO3hK3xgRLC+NUYvveBLz1I54clo+gEUdoCPzPjeWVi7w/YYJr66k+4BBL0KRrmwAgV2hDDgynpL9V6o+6H3VX8yg5BDH6YRiEQFkEUWwPcJ/moMkuLuuxEGaUb0yvGbo06rdyaq/WZmvJB3I0wSgtoO5O3swnmmM7S5fh4nMcr8EbY6slqx8j1Fe7xekqjJ4Pb39q08v0ZKW3C9kgF7s8VKXmap3u//+ft3OkZUPcF8kaITH7nkKaYXRWpdmjGrSrtHyHqy2WVc8UzpsVd34M5qkAANy/L/hMqy5gTg8NbK6KD6ckIPVucpppP5yQB+uCXI+jz2eW/GpWYutaG43Nhq9bElf+/fYBYNdywftkR5KTCBifIU711vodlxU5KcuPDGPM4brJvGkSHu78zxDXyoEKdpw298RBdwtmW8RPGdHH5GVFpiYAAZSpKXfW9qfkPuB4ZEtiCaQvMGJLM0tqiN9t2HGGVtuf2/G2Ao3TLdLvQIZX2m7nF9yCtQeSfkd1YKafSpePmyXZ4dPrfNFxbHh9IZ/loCIj7uzKlAatdo43fIfr5Z6BQxn4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
